//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

namespace PCMTandberg.BusinessEntities
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Web.Services.WebServiceAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "PCMTandbergSvcSoap", Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public abstract partial class PCMTandbergSvc : System.Web.Services.WebService
    {

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://cesium.cisco.com/PCMTandbergService/GetLicense", RequestNamespace = "https://cesium.cisco.com/PCMTandbergService", ResponseNamespace = "https://cesium.cisco.com/PCMTandbergService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("objGetLicenseResponse")]
        public abstract DFLicenseResponse GetLicense(DFLicenseRequest objDFLicenseRequest);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://cesium.cisco.com/PCMTandbergService/GetLicenses", RequestNamespace = "https://cesium.cisco.com/PCMTandbergService", ResponseNamespace = "https://cesium.cisco.com/PCMTandbergService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("objLicenseResponse")]
        public abstract LicenseResponse GetLicenses(LicenseRequest objLicenseRequest);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://cesium.cisco.com/PCMTandbergService/GetSoftwareVersions", RequestNamespace = "https://cesium.cisco.com/PCMTandbergService", ResponseNamespace = "https://cesium.cisco.com/PCMTandbergService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("objGetSoftwareVersionsResponse")]
        public abstract GetSoftwareVersionsResponse GetSoftwareVersions(GetSoftwareVersionsRequest objGetSoftwareVersionsRequest);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://cesium.cisco.com/PCMTandbergService/ValidateSKU", RequestNamespace = "https://cesium.cisco.com/PCMTandbergService", ResponseNamespace = "https://cesium.cisco.com/PCMTandbergService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("objValidateSKUResponse")]
        public abstract ValidateSKUResponse ValidateSKU(ValidateSKURequest objValidateSKURequest);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://cesium.cisco.com/PCMTandbergService/SoftDeleteLicenses", RequestNamespace = "https://cesium.cisco.com/PCMTandbergService", ResponseNamespace = "https://cesium.cisco.com/PCMTandbergService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("objSoftDeleteLicenses")]
        public abstract SoftDeleteLicensesResponse SoftDeleteLicenses(SoftDeleteLicensesRequest objSoftDeleteLicensesRequest);


        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://cesium.cisco.com/PCMTandbergService/GetParentChildAssociation", RequestNamespace = "https://cesium.cisco.com/PCMTandbergService", ResponseNamespace = "https://cesium.cisco.com/PCMTandbergService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("objGetParentChildAssociationResponse")]
        public abstract GetParentChildAssociationResponse GetParentChildAssociation(GetParentChildAssociationRequest objGetParentChildAssociationRequest);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://cesium.cisco.com/PCMTandbergService/RMASwap", RequestNamespace = "https://cesium.cisco.com/PCMTandbergService", ResponseNamespace = "https://cesium.cisco.com/PCMTandbergService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("objRMASwapResponse")]
        public abstract RMASwapResponse RMASwap(RMASwapRequest objRMASwapRequest);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://cesium.cisco.com/PCMTandbergService/SetSKUMetadata", RequestNamespace = "https://cesium.cisco.com/PCMTandbergService", ResponseNamespace = "https://cesium.cisco.com/PCMTandbergService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("objSetSKUMetadataResponse")]
        public abstract SetSKUMetadataResponse SetSKUMetadata(SetSKUMetadataRequest objSetSKUMetadataRequest);

        
             /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://cesium.cisco.com/PCMTandbergService/GetSNHierarchy", RequestNamespace = "https://cesium.cisco.com/PCMTandbergService", ResponseNamespace = "https://cesium.cisco.com/PCMTandbergService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("objGetSNHierarchyResponse")]
        public abstract GetSNHierarchyResponse GetSNHierarchy(GetSNHierarchyRequest objGetSNHierarchyRequest);

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class DFLicenseRequest
    {

        private string requestIDField;

        private string requestingSystemField;

        private System.DateTime requestDateTimeField;

        private string sNumField;

        private string macAddressField;

        private string sKUIDField;

        private string versionField;

        private string seedField;

        private string algTypeField;

        private System.DateTime expDateField;

        private bool expDateFieldSpecified;

        private int indexField;

        private bool indexFieldSpecified;

        private int qtyField;

        private bool qtyFieldSpecified;

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string RequestingSystem
        {
            get
            {
                return this.requestingSystemField;
            }
            set
            {
                this.requestingSystemField = value;
            }
        }

        /// <remarks/>
        public System.DateTime RequestDateTime
        {
            get
            {
                return this.requestDateTimeField;
            }
            set
            {
                this.requestDateTimeField = value;
            }
        }

        /// <remarks/>
        public string SNum
        {
            get
            {
                return this.sNumField;
            }
            set
            {
                this.sNumField = value;
            }
        }

        /// <remarks/>
        public string MacAddress
        {
            get
            {
                return this.macAddressField;
            }
            set
            {
                this.macAddressField = value;
            }
        }

        /// <remarks/>
        public string SKUID
        {
            get
            {
                return this.sKUIDField;
            }
            set
            {
                this.sKUIDField = value;
            }
        }

        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string Seed
        {
            get
            {
                return this.seedField;
            }
            set
            {
                this.seedField = value;
            }
        }

        /// <remarks/>
        public string AlgType
        {
            get
            {
                return this.algTypeField;
            }
            set
            {
                this.algTypeField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ExpDate
        {
            get
            {
                return this.expDateField;
            }
            set
            {
                this.expDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpDateSpecified
        {
            get
            {
                return this.expDateFieldSpecified;
            }
            set
            {
                this.expDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int Index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndexSpecified
        {
            get
            {
                return this.indexFieldSpecified;
            }
            set
            {
                this.indexFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int Qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtySpecified
        {
            get
            {
                return this.qtyFieldSpecified;
            }
            set
            {
                this.qtyFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class SetSKUMetadataResponse
    {

        private string requestIDField;

        private string responseIDField;

        private System.DateTime responseDateTimeField;

        private int responseStatusField;

        private string responseMessageField;

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string ResponseID
        {
            get
            {
                return this.responseIDField;
            }
            set
            {
                this.responseIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ResponseDateTime
        {
            get
            {
                return this.responseDateTimeField;
            }
            set
            {
                this.responseDateTimeField = value;
            }
        }

        /// <remarks/>
        public int ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }

        /// <remarks/>
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class Software
    {

         private string versionField;

        private string versionTypeField;

        private int versionSeqNoField;

        private string versionReleaseClassificationField;

        private string imageUrlField;

        private System.DateTime releaseDateField;

        private bool releaseDateFieldSpecified;


        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string VersionType
        {
            get
            {
                return this.versionTypeField;
            }
            set
            {
                this.versionTypeField = value;
            }
        }

        /// <remarks/>
        public int VersionSeqNo
        {
            get
            {
                return this.versionSeqNoField;
            }
            set
            {
                this.versionSeqNoField = value;
            }
        }

        /// <remarks/>
        public string VersionReleaseClassification
        {
            get
            {
                return this.versionReleaseClassificationField;
            }
            set
            {
                this.versionReleaseClassificationField = value;
            }
        }

        /// <remarks/>
        public string ImageUrl
        {
            get
            {
                return this.imageUrlField;
            }
            set
            {
                this.imageUrlField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ReleaseDate
        {
            get
            {
                return this.releaseDateField;
            }
            set
            {
                this.releaseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReleaseDateSpecified
        {
            get
            {
                return this.releaseDateFieldSpecified;
            }
            set
            {
                this.releaseDateFieldSpecified = value;
            }
        }

        
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class SKUMetadata
    {

        private string SKUidField;
      
        private string tAASysPartNoField;

        private string tAASysPartNameField;

        private string tAAPartNoField;

        private string tAAPartNameField;

        private string ActionTypeField;

        private int ProductTypeField;

        private int qtyField;

        private bool qtyFieldSpecified;

        private string algIDField;

        private string algDescField;

        private string seedField;

        private string TaaTypeField;

        private int AllowManyField;

        private Software softwareMetadataField;

        private string CreatedByField;

        private DateTime CreatedOnField;

        private string UpdatedByField;

        private DateTime UpdatedOnField;


        /// <remarks/>
        public string SKUID
        {
            get
            {
                return this.SKUidField;
            }
            set
            {
                this.SKUidField = value;
            }
        }

         /// <remarks/>
        public string TAASysPartNo
        {
            get
            {
                return this.tAASysPartNoField;
            }
            set
            {
                this.tAASysPartNoField = value;
            }
        }

        /// <remarks/>
        public string TAASysPartName
        {
            get
            {
                return this.tAASysPartNameField;
            }
            set
            {
                this.tAASysPartNameField = value;
            }
        }

        /// <remarks/>
        public string TAAPartNo
        {
            get
            {
                return this.tAAPartNoField;
            }
            set
            {
                this.tAAPartNoField = value;
            }
        }

        /// <remarks/>
        public string TAAPartName
        {
            get
            {
                return this.tAAPartNameField;
            }
            set
            {
                this.tAAPartNameField = value;
            }
        }

        /// <remarks/>
        public string ActionType
        {
            get
            {
                return this.ActionTypeField;
            }
            set
            {
                this.ActionTypeField = value;
            }
        }

        /// <remarks/>
        public int ProductType
        {
            get
            {
                return this.ProductTypeField;
            }
            set
            {
                this.ProductTypeField = value;
            }
        }

        /// <remarks/>
        public int Qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }

        ///// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool QtySpecified
        //{
        //    get
        //    {
        //        return this.qtyFieldSpecified;
        //    }
        //    set
        //    {
        //        this.qtyFieldSpecified = value;
        //    }
        //}

        /// <remarks/>
        public string AlgID
        {
            get
            {
                return this.algIDField;
            }
            set
            {
                this.algIDField = value;
            }
        }

        /// <remarks/>
        public string AlgDesc
        {
            get
            {
                return this.algDescField;
            }
            set
            {
                this.algDescField = value;
            }
        }

        /// <remarks/>
        public string Seed
        {
            get
            {
                return this.seedField;
            }
            set
            {
                this.seedField = value;
            }
        }

        /// <remarks/>
        public string TaaType
        {
            get
            {
                return this.TaaTypeField;
            }
            set
            {
                this.TaaTypeField = value;
            }
        }

        /// <remarks/>
        public int AllowMany
        {
            get
            {
                return this.AllowManyField;
            }
            set
            {
                this.AllowManyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoftwareMetadata")]
        public Software SoftwareMetadata
        {
            get
            {
                return this.softwareMetadataField;
            }
            set
            {
                this.softwareMetadataField = value;
            }
        }

        /// <remarks/>
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }

        /// <remarks/>
        public DateTime CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }

        /// <remarks/>
        public string UpdatedBy
        {
            get
            {
                return this.UpdatedByField;
            }
            set
            {
                this.UpdatedByField = value;
            }
        }

        /// <remarks/>
        public DateTime UpdatedOn
        {
            get
            {
                return this.UpdatedOnField;
            }
            set
            {
                this.UpdatedOnField = value;
            }
        }

       
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class SetSKUMetadataRequest
    {

        private string requestIDField;

        private string requestingSystemField;

        private DateTime requestDateTimeField;

        private SKUMetadata SKUMetadataFeild;

        

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string RequestingSystem
        {
            get
            {
                return this.requestingSystemField;
            }
            set
            {
                this.requestingSystemField = value;
            }
        }

        /// <remarks/>
        public DateTime RequestDateTime
        {
            get
            {
                return this.requestDateTimeField;
            }
            set
            {
                this.requestDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SKUMetadata")]
        public SKUMetadata SKUMetadata
        {
            get
            {
                return this.SKUMetadataFeild;
            }
            set
            {
                this.SKUMetadataFeild = value;
            }
        }

        
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class LicenseInfo
    {

        private string sKUTypeField;

        private string licenseKeyField;

        private string imageUrlField;

        private int qtyField;

        private bool qtyFieldSpecified;

        private int versionSeqNoField;

        private string versionField;

        private string versionTypeField;

        private string versionReleaseClassificationField;

        private bool isShippedVersionField;

        private System.DateTime releaseDateField;

        private bool releaseDateFieldSpecified;

        private string sKUIDField;

        /// <remarks/>
        public string SKUType
        {
            get
            {
                return this.sKUTypeField;
            }
            set
            {
                this.sKUTypeField = value;
            }
        }

        /// <remarks/>
        public string LicenseKey
        {
            get
            {
                return this.licenseKeyField;
            }
            set
            {
                this.licenseKeyField = value;
            }
        }

        /// <remarks/>
        public string ImageUrl
        {
            get
            {
                return this.imageUrlField;
            }
            set
            {
                this.imageUrlField = value;
            }
        }

        /// <remarks/>
        public int Qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtySpecified
        {
            get
            {
                return this.qtyFieldSpecified;
            }
            set
            {
                this.qtyFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int VersionSeqNo
        {
            get
            {
                return this.versionSeqNoField;
            }
            set
            {
                this.versionSeqNoField = value;
            }
        }

        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string VersionType
        {
            get
            {
                return this.versionTypeField;
            }
            set
            {
                this.versionTypeField = value;
            }
        }

        /// <remarks/>
        public string VersionReleaseClassification
        {
            get
            {
                return this.versionReleaseClassificationField;
            }
            set
            {
                this.versionReleaseClassificationField = value;
            }
        }

        /// <remarks/>
        public bool IsShippedVersion
        {
            get
            {
                return this.isShippedVersionField;
            }
            set
            {
                this.isShippedVersionField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ReleaseDate
        {
            get
            {
                return this.releaseDateField;
            }
            set
            {
                this.releaseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReleaseDateSpecified
        {
            get
            {
                return this.releaseDateFieldSpecified;
            }
            set
            {
                this.releaseDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SKUID
        {
            get
            {
                return this.sKUIDField;
            }
            set
            {
                this.sKUIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class RMASwapResponse
    {

        private string requestIDField;

        private string responseIDField;

        private System.DateTime responseDateTimeField;

        private int responseStatusField;

        private string responseMessageField;

        private LicenseInfo[] licensesField;

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string ResponseID
        {
            get
            {
                return this.responseIDField;
            }
            set
            {
                this.responseIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ResponseDateTime
        {
            get
            {
                return this.responseDateTimeField;
            }
            set
            {
                this.responseDateTimeField = value;
            }
        }

        /// <remarks/>
        public int ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }

        /// <remarks/>
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Licenses")]
        public LicenseInfo[] Licenses
        {
            get
            {
                return this.licensesField;
            }
            set
            {
                this.licensesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class RMASwapRequest
    {

        private string requestIDField;

        private string requestingSystemField;

        private System.DateTime requestDateTimeField;

        private string sourceLicenseSNumField;

        private string destLicenseSNumField;

        private string rMANoField;

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string RequestingSystem
        {
            get
            {
                return this.requestingSystemField;
            }
            set
            {
                this.requestingSystemField = value;
            }
        }

        /// <remarks/>
        public System.DateTime RequestDateTime
        {
            get
            {
                return this.requestDateTimeField;
            }
            set
            {
                this.requestDateTimeField = value;
            }
        }

        /// <remarks/>
        public string SourceLicenseSNum
        {
            get
            {
                return this.sourceLicenseSNumField;
            }
            set
            {
                this.sourceLicenseSNumField = value;
            }
        }

        /// <remarks/>
        public string DestLicenseSNum
        {
            get
            {
                return this.destLicenseSNumField;
            }
            set
            {
                this.destLicenseSNumField = value;
            }
        }

        /// <remarks/>
        public string RMANo
        {
            get
            {
                return this.rMANoField;
            }
            set
            {
                this.rMANoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class SNums
    {

        private string sNumField;

        private string parentSNumField;

        private string levelField;

        private bool isLicensableSNumField;

        private string macAddressField;

        private string uuttype;

        private SKUDetailInfo[] sKUField;

        /// <remarks/>
        public string SNum
        {
            get
            {
                return this.sNumField;
            }
            set
            {
                this.sNumField = value;
            }
        }

        /// <remarks/>
        public string ParentSNum
        {
            get
            {
                return this.parentSNumField;
            }
            set
            {
                this.parentSNumField = value;
            }
        }

        /// <remarks/>
        public string Level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }

        /// <remarks/>
        public bool IsLicensableSNum
        {
            get
            {
                return this.isLicensableSNumField;
            }
            set
            {
                this.isLicensableSNumField = value;
            }
        }

        /// <remarks/>
        public string MacAddress
        {
            get
            {
                return this.macAddressField;
            }
            set
            {
                this.macAddressField = value;
            }
        }

        /// <remarks/>
        public string UutType
        {
            get
            {
                return this.uuttype;
            }
            set
            {
                this.uuttype = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SKU")]
        public SKUDetailInfo[] SKU
        {
            get
            {
                return this.sKUField;
            }
            set
            {
                this.sKUField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class SKUDetailInfo
    {

        private string sKUNameField;

        private string tAAPartNoField;

        private string tAAPartNameField;

        private int qtyField;

        private bool qtyFieldSpecified;

        private System.DateTime UpdatedTimestampField;

        private bool UpdatedTimeStampSpecified;

        private string optionLicenseKeyField;

        private VersionInfoWithLicense[] versionListField;

        private string sKUIDField;

        private string sKUTypeField;

        /// <remarks/>
        public string SKUName
        {
            get
            {
                return this.sKUNameField;
            }
            set
            {
                this.sKUNameField = value;
            }
        }

        /// <remarks/>
        public string TAAPartNo
        {
            get
            {
                return this.tAAPartNoField;
            }
            set
            {
                this.tAAPartNoField = value;
            }
        }

        /// <remarks/>
        public string TAAPartName
        {
            get
            {
                return this.tAAPartNameField;
            }
            set
            {
                this.tAAPartNameField = value;
            }
        }

        /// <remarks/>
        public int Qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtySpecified
        {
            get
            {
                return this.qtyFieldSpecified;
            }
            set
            {
                this.qtyFieldSpecified = value;
            }
        }

        public System.DateTime UpdatedTimestamp
        {
            get
            {
                return this.UpdatedTimestampField;
            }
            set
            {
                this.UpdatedTimestampField = value;
            }
        }
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpdatedTimestampSpecified
        {
            get
            {
                return this.UpdatedTimeStampSpecified;
            }
            set
            {
                this.UpdatedTimeStampSpecified = value;
            }
        }


        /// <remarks/>
        public string OptionLicenseKey
        {
            get
            {
                return this.optionLicenseKeyField;
            }
            set
            {
                this.optionLicenseKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VersionList")]
        public VersionInfoWithLicense[] VersionList
        {
            get
            {
                return this.versionListField;
            }
            set
            {
                this.versionListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SKUID
        {
            get
            {
                return this.sKUIDField;
            }
            set
            {
                this.sKUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SKUType
        {
            get
            {
                return this.sKUTypeField;
            }
            set
            {
                this.sKUTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class VersionInfoWithLicense
    {

        private string versionPartNoField;

        private string versionPartNameField;

        private int versionSeqNoField;

        private string versionField;

        private string versionTypeField;

        private string versionReleaseClassificationField;

        private bool isShippedVersionField;

        private string imageUrlField;

        private string licenseKeyField;

        private System.DateTime releaseDateField;

        private bool releaseDateFieldSpecified;

        private System.DateTime VersionUpgradedDateField;

        private bool VersionUpgradedDateSpecified;

        /// <remarks/>
        public string VersionPartNo
        {
            get
            {
                return this.versionPartNoField;
            }
            set
            {
                this.versionPartNoField = value;
            }
        }

        /// <remarks/>
        public string VersionPartName
        {
            get
            {
                return this.versionPartNameField;
            }
            set
            {
                this.versionPartNameField = value;
            }
        }

        /// <remarks/>
        public int VersionSeqNo
        {
            get
            {
                return this.versionSeqNoField;
            }
            set
            {
                this.versionSeqNoField = value;
            }
        }

        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string VersionType
        {
            get
            {
                return this.versionTypeField;
            }
            set
            {
                this.versionTypeField = value;
            }
        }

        /// <remarks/>
        public string VersionReleaseClassification
        {
            get
            {
                return this.versionReleaseClassificationField;
            }
            set
            {
                this.versionReleaseClassificationField = value;
            }
        }

        /// <remarks/>
        public bool IsShippedVersion
        {
            get
            {
                return this.isShippedVersionField;
            }
            set
            {
                this.isShippedVersionField = value;
            }
        }

        /// <remarks/>
        public string ImageUrl
        {
            get
            {
                return this.imageUrlField;
            }
            set
            {
                this.imageUrlField = value;
            }
        }

        /// <remarks/>
        public string LicenseKey
        {
            get
            {
                return this.licenseKeyField;
            }
            set
            {
                this.licenseKeyField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ReleaseDate
        {
            get
            {
                return this.releaseDateField;
            }
            set
            {
                this.releaseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReleaseDateSpecified
        {
            get
            {
                return this.releaseDateFieldSpecified;
            }
            set
            {
                this.releaseDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime VersionUpgradedOn
        {
            get
            {
                return this.VersionUpgradedDateField;
            }
            set
            {
                this.VersionUpgradedDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VersionUpgradedOnSpecified
        {
            get
            {
                return this.VersionUpgradedDateSpecified;
            }
            set
            {
                this.VersionUpgradedDateSpecified = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class SNumsAssociation
    {

        private int statusField;

        private string messageField;

        private SNums[] sNumListField;

        private string sNumField;

        private string LicsNumField;

        /// <remarks/>
        public int Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SNumList")]
        public SNums[] SNumList
        {
            get
            {
                return this.sNumListField;
            }
            set
            {
                this.sNumListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SNum
        {
            get
            {
                return this.sNumField;
            }
            set
            {
                this.sNumField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LicensableSNum
        {
            get
            {
                return this.LicsNumField;
            }
            set
            {
                this.LicsNumField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class GetParentChildAssociationResponse
    {

        private string requestIDField;

        private string responseIDField;

        private System.DateTime responseDateTimeField;

        private int responseStatusField;

        private string responseMessageField;

        private SNumsAssociation[] associationField;

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string ResponseID
        {
            get
            {
                return this.responseIDField;
            }
            set
            {
                this.responseIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ResponseDateTime
        {
            get
            {
                return this.responseDateTimeField;
            }
            set
            {
                this.responseDateTimeField = value;
            }
        }

        /// <remarks/>
        public int ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }

        /// <remarks/>
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Association")]
        public SNumsAssociation[] Association
        {
            get
            {
                return this.associationField;
            }
            set
            {
                this.associationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class GetParentChildAssociationRequest
    {

        private string requestIDField;

        private string requestingSystemField;

        private System.DateTime requestDateTimeField;

        private string[] sNumField;

        private Filters Filters;

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string RequestingSystem
        {
            get
            {
                return this.requestingSystemField;
            }
            set
            {
                this.requestingSystemField = value;
            }
        }

        /// <remarks/>
        public System.DateTime RequestDateTime
        {
            get
            {
                return this.requestDateTimeField;
            }
            set
            {
                this.requestDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SNum")]
        public string[] SNum
        {
            get
            {
                return this.sNumField;
            }
            set
            {
                this.sNumField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Filter")]
        public Filters Filter
        {
            get
            {
                return this.Filters;
            }
            set
            {
                this.Filters = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class SNumsAssociationSN
    {

        private int statusField;

        private string messageField;

        private SNumsHierarchy[] sNumListField;

        private string sNumField;

        
        /// <remarks/>
        public int Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SNumList")]
        public SNumsHierarchy[] SNumList
        {
            get
            {
                return this.sNumListField;
            }
            set
            {
                this.sNumListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SNum
        {
            get
            {
                return this.sNumField;
            }
            set
            {
                this.sNumField = value;
            }
        }

   
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class SNumsHierarchy
    {

        private string sNumField;

        private string parentSNumField;

        private string levelField;

        private string macAddressField;

        private string uuttype;

        private string recTime;

        /// <remarks/>
        public string SNum
        {
            get
            {
                return this.sNumField;
            }
            set
            {
                this.sNumField = value;
            }
        }

        /// <remarks/>
        public string ParentSNum
        {
            get
            {
                return this.parentSNumField;
            }
            set
            {
                this.parentSNumField = value;
            }
        }

        /// <remarks/>
        public string Level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }

        /// <remarks/>
        public string MacAddress
        {
            get
            {
                return this.macAddressField;
            }
            set
            {
                this.macAddressField = value;
            }
        }

        /// <remarks/>
        public string UutType
        {
            get
            {
                return this.uuttype;
            }
            set
            {
                this.uuttype = value;
            }
        }

        /// <remarks/>
        public string RecTime
        {
            get
            {
                return this.recTime;
            }
            set
            {
                this.recTime = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class GetSNHierarchyResponse
    {

        private string requestIDField;

        private string responseIDField;

        private System.DateTime responseDateTimeField;

        private int responseStatusField;

        private string responseMessageField;

        private SNumsAssociationSN[] associationField;

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string ResponseID
        {
            get
            {
                return this.responseIDField;
            }
            set
            {
                this.responseIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ResponseDateTime
        {
            get
            {
                return this.responseDateTimeField;
            }
            set
            {
                this.responseDateTimeField = value;
            }
        }

        /// <remarks/>
        public int ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }

        /// <remarks/>
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Association")]
        public SNumsAssociationSN[] Association
        {
            get
            {
                return this.associationField;
            }
            set
            {
                this.associationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class GetSNHierarchyRequest
    {

        private string requestIDField;

        private string requestingSystemField;

        private System.DateTime requestDateTimeField;

        private string[] sNumField;       

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string RequestingSystem
        {
            get
            {
                return this.requestingSystemField;
            }
            set
            {
                this.requestingSystemField = value;
            }
        }

        /// <remarks/>
        public System.DateTime RequestDateTime
        {
            get
            {
                return this.requestDateTimeField;
            }
            set
            {
                this.requestDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SNum")]
        public string[] SNum
        {
            get
            {
                return this.sNumField;
            }
            set
            {
                this.sNumField = value;
            }
        }
      
    }




    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class Filters
    {


        private LookUpFilters LookupFilters;

        /// <remarks/>
        [System.Xml.Serialization.XmlElement("LookupFilter")]
        public LookUpFilters LookupFilter
        {
            get
            {
                return this.LookupFilters;
            }
            set
            {
                this.LookupFilters = value;
            }
        }


    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class LookUpFilters
    {
        private string FilterNames;

        private string FilterValues;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("")]
        public string FilterName
        {
            get
            {
                return this.FilterNames;
            }
            set
            {
                this.FilterNames = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("")]
        public string FilterValue
        {
            get
            {
                return this.FilterValues;
            }
            set
            {
                this.FilterValues = value;
            }
        }


    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class VersionInfoWithImageUrl
    {

        private int versionSeqNoField;

        private string versionField;

        private string versionTypeField;

        private string versionReleaseClassificationField;

        private bool isShippedVersionField;

        private System.DateTime releaseDateField;

        private bool releaseDateFieldSpecified;

        private string imageUrlField;

        /// <remarks/>
        public int VersionSeqNo
        {
            get
            {
                return this.versionSeqNoField;
            }
            set
            {
                this.versionSeqNoField = value;
            }
        }

        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string VersionType
        {
            get
            {
                return this.versionTypeField;
            }
            set
            {
                this.versionTypeField = value;
            }
        }

        /// <remarks/>
        public string VersionReleaseClassification
        {
            get
            {
                return this.versionReleaseClassificationField;
            }
            set
            {
                this.versionReleaseClassificationField = value;
            }
        }

        /// <remarks/>
        public bool IsShippedVersion
        {
            get
            {
                return this.isShippedVersionField;
            }
            set
            {
                this.isShippedVersionField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ReleaseDate
        {
            get
            {
                return this.releaseDateField;
            }
            set
            {
                this.releaseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReleaseDateSpecified
        {
            get
            {
                return this.releaseDateFieldSpecified;
            }
            set
            {
                this.releaseDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string ImageUrl
        {
            get
            {
                return this.imageUrlField;
            }
            set
            {
                this.imageUrlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class GetSoftwareVersionsResponse
    {

        private string requestIDField;

        private string responseIDField;

        private System.DateTime responseDateTimeField;

        private int responseStatusField;

        private string responseMessageField;

        private string sKUIDField;

        private VersionInfoWithImageUrl[] availableVersionField;

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string ResponseID
        {
            get
            {
                return this.responseIDField;
            }
            set
            {
                this.responseIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ResponseDateTime
        {
            get
            {
                return this.responseDateTimeField;
            }
            set
            {
                this.responseDateTimeField = value;
            }
        }

        /// <remarks/>
        public int ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }

        /// <remarks/>
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }

        /// <remarks/>
        public string SKUID
        {
            get
            {
                return this.sKUIDField;
            }
            set
            {
                this.sKUIDField = value;
            }
        }
        

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AvailableVersion")]
        public VersionInfoWithImageUrl[] AvailableVersion
        {
            get
            {
                return this.availableVersionField;
            }
            set
            {
                this.availableVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class GetSoftwareVersionsRequest
    {

        private string requestIDField;

        private string requestingSystemField;

        private System.DateTime requestDateTimeField;

        private string sKUIDField;
        
        private string versionFilterField;

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string RequestingSystem
        {
            get
            {
                return this.requestingSystemField;
            }
            set
            {
                this.requestingSystemField = value;
            }
        }

        /// <remarks/>
        public System.DateTime RequestDateTime
        {
            get
            {
                return this.requestDateTimeField;
            }
            set
            {
                this.requestDateTimeField = value;
            }
        }

        /// <remarks/>
        public string SKUID
        {
            get
            {
                return this.sKUIDField;
            }
            set
            {
                this.sKUIDField = value;
            }
        }

        /// <remarks/>
        public string VersionFilter
        {
            get
            {
                return this.versionFilterField;
            }
            set
            {
                this.versionFilterField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class ValidateSKUResponse
    {

        private string requestIDField;

        private string responseIDField;

        private System.DateTime responseDateTimeField;

        private int responseStatusField;

        private string responseMessageField;

        //private string sKUIDField;
        private Response_SKUVersionInfo[] sKUIDField;

        //private VersionInfoWithImageUrl[] availableVersionField;

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string ResponseID
        {
            get
            {
                return this.responseIDField;
            }
            set
            {
                this.responseIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ResponseDateTime
        {
            get
            {
                return this.responseDateTimeField;
            }
            set
            {
                this.responseDateTimeField = value;
            }
        }

        /// <remarks/>
        public int ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }

        /// <remarks/>
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("SKU")]
        public Response_SKUVersionInfo[] SKUID
        {
            get
            {
                return this.sKUIDField;
            }
            set
            {
                this.sKUIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class ValidateSKURequest
    {

        private string requestIDField;

        private string requestingSystemField;

        private System.DateTime requestDateTimeField;

        //private string sKUIDField;
        private SKUVersionInfo[] sKUIDField;
        //private string versionFilterField;

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string RequestingSystem
        {
            get
            {
                return this.requestingSystemField;
            }
            set
            {
                this.requestingSystemField = value;
            }
        }

        /// <remarks/>
        public System.DateTime RequestDateTime
        {
            get
            {
                return this.requestDateTimeField;
            }
            set
            {
                this.requestDateTimeField = value;
            }
        }

        ///// <remarks/>
        //public string SKUID
        //{
        //    get
        //    {
        //        return this.sKUIDField;
        //    }
        //    set
        //    {
        //        this.sKUIDField = value;
        //    }
        //}
        [System.Xml.Serialization.XmlElementAttribute("SKU")]
        public SKUVersionInfo[] SKUID
        {
            get
            {
                return this.sKUIDField;
            }
            set
            {
                this.sKUIDField = value;
            }
        }


        ///// <remarks/>
        //public string VersionFilter
        //{
        //    get
        //    {
        //        return this.versionFilterField;
        //    }
        //    set
        //    {
        //        this.versionFilterField = value;
        //    }
        //}
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class SoftDeleteLicensesRequest
    {

        private string requestIDField;

        private string requestingSystemField;

        private System.DateTime requestDateTimeField;

        private string sNumField;

       private string  SKUField;

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string RequestingSystem
        {
            get
            {
                return this.requestingSystemField;
            }
            set
            {
                this.requestingSystemField = value;
            }
        }

        /// <remarks/>
        public System.DateTime RequestDateTime
        {
            get
            {
                return this.requestDateTimeField;
            }
            set
            {
                this.requestDateTimeField = value;
            }
        }

        /// <remarks/>
        public string SNum
        {
            get
            {
                return this.sNumField;
            }
            set
            {
                this.sNumField = value;
            }
        }


        
        public string SKU
        {
            get
            {
                return this.SKUField;
            }
            set
            {
                this.SKUField = value;
            }
        }


    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class SoftDeleteLicensesResponse
    {

        private string requestIDField;

        private string responseIDField;

        private System.DateTime responseDateTimeField;

        private int responseStatusField;

        private string responseMessageField;

        private string sNumField;

        private string SKUField;    

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string ResponseID
        {
            get
            {
                return this.responseIDField;
            }
            set
            {
                this.responseIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ResponseDateTime
        {
            get
            {
                return this.responseDateTimeField;
            }
            set
            {
                this.responseDateTimeField = value;
            }
        }

        /// <remarks/>
        public int ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }

        /// <remarks/>
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }

        /// <remarks/>
        public string SNum
        {
            get
            {
                return this.sNumField;
            }
            set
            {
                this.sNumField = value;
            }
        }

                
        public string SKU
        {
            get
            {
                return this.SKUField;
            }
            set
            {
                this.SKUField = value;
            }
        }

        
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class UnitLicenseInfo
    {

        private int statusField;

        private string messageField;

        private SKUDetailInfo[] sKUField;

        private string sNumField;

        private string licensableSNumField;

        /// <remarks/>
        public int Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SKU")]
        public SKUDetailInfo[] SKU
        {
            get
            {
                return this.sKUField;
            }
            set
            {
                this.sKUField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SNum
        {
            get
            {
                return this.sNumField;
            }
            set
            {
                this.sNumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LicensableSNum
        {
            get
            {
                return this.licensableSNumField;
            }
            set
            {
                this.licensableSNumField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class LicenseResponse
    {

        private string requestIDField;

        private string responseIDField;

        private System.DateTime responseDateTimeField;

        private int responseStatusField;

        private string responseMessageField;

        private UnitLicenseInfo[] unitLicenseInfoField;

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string ResponseID
        {
            get
            {
                return this.responseIDField;
            }
            set
            {
                this.responseIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ResponseDateTime
        {
            get
            {
                return this.responseDateTimeField;
            }
            set
            {
                this.responseDateTimeField = value;
            }
        }

        /// <remarks/>
        public int ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }

        /// <remarks/>
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UnitLicenseInfo")]
        public UnitLicenseInfo[] UnitLicenseInfo
        {
            get
            {
                return this.unitLicenseInfoField;
            }
            set
            {
                this.unitLicenseInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class SKUInfo
    {

        private string sKUIDField;

        private int qtyField;

        private bool qtyFieldSpecified;

        private string versionFilterField;

        /// <remarks/>
        public string SKUID
        {
            get
            {
                return this.sKUIDField;
            }
            set
            {
                this.sKUIDField = value;
            }
        }

        /// <remarks/>
        public int Qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtySpecified
        {
            get
            {
                return this.qtyFieldSpecified;
            }
            set
            {
                this.qtyFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string VersionFilter
        {
            get
            {
                return this.versionFilterField;
            }
            set
            {
                this.versionFilterField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class SKUVersionInfo
    {

        private string sKUIDField;
        private string versionFilterField;


        /// <remarks/>
        public string SKUID
        {
            get
            {
                return this.sKUIDField;
            }
            set
            {
                this.sKUIDField = value;
            }
        }
        /// <remarks/>
        public string VersionFilter
        {
            get
            {
                return this.versionFilterField;
            }
            set
            {
                this.versionFilterField = value;
            }
        }


    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class Response_SKUVersionInfo
    {

        private string sKUIDField;
        private int responseStatusField;
        private string responseMessageField;
        private VersionInfoWithImageUrl[] availableVersionField;

        /// <remarks/>
        public int ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }

        /// <remarks/>
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }
        /// <remarks/>
        public string SKUID
        {
            get
            {
                return this.sKUIDField;
            }
            set
            {
                this.sKUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SKU")]
        public VersionInfoWithImageUrl[] AvailableVersion
        {
            get
            {
                return this.availableVersionField;
            }
            set
            {
                this.availableVersionField = value;
            }
        }


    }



    
     /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class UnitInfo
    {

        private string sNumField;

        private SKUInfo[] sKUField;

        private string[] macAddressField;

        private System.DateTime expiryDateField;

        private bool expiryDateFieldSpecified;

        /// <remarks/>
        public string SNum
        {
            get
            {
                return this.sNumField;
            }
            set
            {
                this.sNumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SKU")]
        public SKUInfo[] SKU
        {
            get
            {
                return this.sKUField;
            }
            set
            {
                this.sKUField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MacAddress")]
        public string[] MacAddress
        {
            get
            {
                return this.macAddressField;
            }
            set
            {
                this.macAddressField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ExpiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiryDateSpecified
        {
            get
            {
                return this.expiryDateFieldSpecified;
            }
            set
            {
                this.expiryDateFieldSpecified = value;
            }
        }


    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class LicenseRequest
    {

        private string requestIDField;

        private string requestingSystemField;

        private System.DateTime requestDateTimeField;

        private UnitInfo[] unitInfoField;

        private bool CheckLicensableSnum;

        private bool CheckLicensableSnumSpecified;

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string RequestingSystem
        {
            get
            {
                return this.requestingSystemField;
            }
            set
            {
                this.requestingSystemField = value;
            }
        }

        /// <remarks/>
        public System.DateTime RequestDateTime
        {
            get
            {
                return this.requestDateTimeField;
            }
            set
            {
                this.requestDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UnitInfo")]
        public UnitInfo[] UnitInfo
        {
            get
            {
                return this.unitInfoField;
            }
            set
            {
                this.unitInfoField = value;
            }
        }
        /// <remarks/>
        public bool CheckLicensableSNUM
        {
            get
            {
                return this.CheckLicensableSnum;
            }
            set
            {
                this.CheckLicensableSnum = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CheckLicensableSNUMSpecified
        {
            get
            {
                return this.CheckLicensableSnumSpecified;
            }
            set
            {
                this.CheckLicensableSnumSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://cesium.cisco.com/PCMTandbergService")]
    public partial class DFLicenseResponse
    {

        private string requestIDField;

        private string responseIDField;

        private System.DateTime responseDateTimeField;

        private int responseStatusField;

        private string responseMessageField;

        private string licenseKeyField;

        /// <remarks/>
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        public string ResponseID
        {
            get
            {
                return this.responseIDField;
            }
            set
            {
                this.responseIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ResponseDateTime
        {
            get
            {
                return this.responseDateTimeField;
            }
            set
            {
                this.responseDateTimeField = value;
            }
        }

        /// <remarks/>
        public int ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }

        /// <remarks/>
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }

        /// <remarks/>
        public string LicenseKey
        {
            get
            {
                return this.licenseKeyField;
            }
            set
            {
                this.licenseKeyField = value;
            }
        }
    }
}