//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 

namespace PCMTandberg.BusinessEntities
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "SigServTandbergServiceSoap", Namespace = "http://cesium.cisco.com/SigServTandberg.wsdl")]
    public partial class SigServTandbergService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback GetLicenseOperationCompleted;

        /// <remarks/>
        public SigServTandbergService()
        {
            this.Url = "http://pcm.cisco.com/SigServTandbergService.asmx";
        }

        /// <remarks/>
        public event GetLicenseCompletedEventHandler GetLicenseCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLicense", RequestNamespace = "http://cesium.cisco.com/SigServTandberg.wsdl", ResponseNamespace = "http://cesium.cisco.com/SigServTandberg.wsdl", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LicResponse GetLicense(LicRequest req)
        {
            object[] results = this.Invoke("GetLicense", new object[] {
                    req});
            return ((LicResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetLicense(LicRequest req, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetLicense", new object[] {
                    req}, callback, asyncState);
        }

        /// <remarks/>
        public LicResponse EndGetLicense(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((LicResponse)(results[0]));
        }

        /// <remarks/>
        public void GetLicenseAsync(LicRequest req)
        {
            this.GetLicenseAsync(req, null);
        }

        /// <remarks/>
        public void GetLicenseAsync(LicRequest req, object userState)
        {
            if ((this.GetLicenseOperationCompleted == null))
            {
                this.GetLicenseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLicenseOperationCompleted);
            }
            this.InvokeAsync("GetLicense", new object[] {
                    req}, this.GetLicenseOperationCompleted, userState);
        }

        private void OnGetLicenseOperationCompleted(object arg)
        {
            if ((this.GetLicenseCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLicenseCompleted(this, new GetLicenseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://cesium.cisco.com/SigServTandberg.wsdl")]
    public partial class LicRequest
    {

        private string sNumField;

        private string mACField;

        private string sKUField;

        private string seedField;

        private string algTypeField;

        private System.DateTime expDateField;

        private bool expDateFieldSpecified;

        private int portsField;

        private bool portsFieldSpecified;

        private int indexField;

        private bool indexFieldSpecified;

        private string versionField;

        private string transactionIDField;

        private System.DateTime requestDateTimeField;

        /// <remarks/>
        public string SNum
        {
            get
            {
                return this.sNumField;
            }
            set
            {
                this.sNumField = value;
            }
        }

        /// <remarks/>
        public string MAC
        {
            get
            {
                return this.mACField;
            }
            set
            {
                this.mACField = value;
            }
        }

        /// <remarks/>
        public string SKU
        {
            get
            {
                return this.sKUField;
            }
            set
            {
                this.sKUField = value;
            }
        }

        /// <remarks/>
        public string Seed
        {
            get
            {
                return this.seedField;
            }
            set
            {
                this.seedField = value;
            }
        }

        /// <remarks/>
        public string AlgType
        {
            get
            {
                return this.algTypeField;
            }
            set
            {
                this.algTypeField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ExpDate
        {
            get
            {
                return this.expDateField;
            }
            set
            {
                this.expDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpDateSpecified
        {
            get
            {
                return this.expDateFieldSpecified;
            }
            set
            {
                this.expDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int Ports
        {
            get
            {
                return this.portsField;
            }
            set
            {
                this.portsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PortsSpecified
        {
            get
            {
                return this.portsFieldSpecified;
            }
            set
            {
                this.portsFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int Index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndexSpecified
        {
            get
            {
                return this.indexFieldSpecified;
            }
            set
            {
                this.indexFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string TransactionID
        {
            get
            {
                return this.transactionIDField;
            }
            set
            {
                this.transactionIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime RequestDateTime
        {
            get
            {
                return this.requestDateTimeField;
            }
            set
            {
                this.requestDateTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://cesium.cisco.com/SigServTandberg.wsdl")]
    public partial class LicResponse
    {

        private string releaseKeyField;

        private string responseMessageField;

        private string responseStatusField;

        private string transactionIDField;

        private System.DateTime responseDateTimeField;

        /// <remarks/>
        public string ReleaseKey
        {
            get
            {
                return this.releaseKeyField;
            }
            set
            {
                this.releaseKeyField = value;
            }
        }

        /// <remarks/>
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }

        /// <remarks/>
        public string ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }

        /// <remarks/>
        public string TransactionID
        {
            get
            {
                return this.transactionIDField;
            }
            set
            {
                this.transactionIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ResponseDateTime
        {
            get
            {
                return this.responseDateTimeField;
            }
            set
            {
                this.responseDateTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void GetLicenseCompletedEventHandler(object sender, GetLicenseCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLicenseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetLicenseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public LicResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((LicResponse)(this.results[0]));
            }
        }
    }
}